#! /bin/bash
# Name : link_to_usr_lib
# Func : link shared library to /usr/lib/ 
# Time : 2016-05-09 13:57:35

# link libxlsreader shared library
LOCAL_XLS=`pwd`/libxls/libxls/src/.libs/libxlsreader.so.1.4.0 
USR_XLS="/usr/lib/libxlsreader.so.1"
USR_XLS1="/usr/lib/libxlsreader.so"
test ! -L $USR_XLS1 #&& sudo ln -sf $LOCAL_XLS $USR_XLS1 
test ! -L $USR_XLS && sudo ln -sf $LOCAL_XLS $USR_XLS 

# link libxlsreader static library
LOCAL_XLS=`pwd`/libxls/libxls/src/libxlsreader.la
USR_XLS=/usr/lib/libxlsreader.la
test ! -L $USR_XLS && sudo ln -sf $LOCAL_XLS $USR_XLS 

# link libxl shared library
LOCAL_XL=`pwd`/libxl/lib/libxl.so
USR_XL=/usr/lib/libxl.so
test ! -L $USR_XL && sudo ln -sf $LOCAL_XL $USR_XL 

# link libsqlite3 shared library 
LOCAL_SQL=`pwd`/libsqlite3/sqlite3/.libs/libsqlite3.so.0.8.6
USR_SQL=/usr/lib/libsqlite3.so
USR_SQL0=/usr/lib/libsqlite3.so.0
test ! -L $USR_SQL0 && sudo ln -sf $LOCAL_SQL $USR_SQL0
test ! -L $USR_SQL && sudo ln -sf $LOCAL_SQL $USR_SQL

# link libsqlite3 static library 
LOCAL_SQL=`pwd`/libsqlite3/sqlite3/.libs/libsqlite3.a
USR_SQL=/usr/lib/libsqlite3.la
test ! -L $USR_SQL && sudo ln -sf $LOCAL_SQL $USR_SQL

# link libsql3 static library 
LOCAL_SQL=`pwd`/../library/sql3/libsql3.so
USR_SQL=/usr/lib/libsqle3.so
test ! -L $USR_SQL && sudo ln -sf $LOCAL_SQL $USR_SQL

# link librwxls static library 
LOCAL_SQL=`pwd`/../library/xls/librwxls.so
USR_SQL=/usr/lib/librwxls.so
test ! -L $USR_SQL && sudo ln -sf $LOCAL_SQL $USR_SQL
